// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApp.Infrastructure;

#nullable disable

namespace WebApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260512130818_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("WebApp.Domain.Area", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Areas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            Code = "CC",
                            Name = "City Center"
                        },
                        new
                        {
                            Id = 2,
                            Active = true,
                            Code = "ND",
                            Name = "North District"
                        },
                        new
                        {
                            Id = 3,
                            Active = true,
                            Code = "SD",
                            Name = "South District"
                        },
                        new
                        {
                            Id = 4,
                            Active = true,
                            Code = "ED",
                            Name = "East District"
                        },
                        new
                        {
                            Id = 5,
                            Active = true,
                            Code = "WD",
                            Name = "West District"
                        });
                });

            modelBuilder.Entity("WebApp.Domain.Incident", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("IncidentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Operator")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SubArea")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Watch")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Area");

                    b.HasIndex("Date");

                    b.HasIndex("Watch");

                    b.ToTable("Incidents");
                });

            modelBuilder.Entity("WebApp.Domain.IncidentResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("IncidentResults");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            Description = "Incident confirmed by operator",
                            Name = "Confirmed"
                        },
                        new
                        {
                            Id = 2,
                            Active = true,
                            Description = "No action needed",
                            Name = "No Action Required"
                        },
                        new
                        {
                            Id = 3,
                            Active = true,
                            Description = "Incident being monitored",
                            Name = "Monitored"
                        },
                        new
                        {
                            Id = 4,
                            Active = true,
                            Description = "Dispersed by police",
                            Name = "Dispersed"
                        },
                        new
                        {
                            Id = 5,
                            Active = true,
                            Description = "Subject arrested",
                            Name = "Arrest"
                        });
                });

            modelBuilder.Entity("WebApp.Domain.IncidentSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("IncidentSources");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            Code = "CCTV",
                            Name = "CCTV Operator"
                        },
                        new
                        {
                            Id = 2,
                            Active = true,
                            Code = "POL",
                            Name = "Police Report"
                        },
                        new
                        {
                            Id = 3,
                            Active = true,
                            Code = "PUB",
                            Name = "Public Report"
                        },
                        new
                        {
                            Id = 4,
                            Active = true,
                            Code = "RL",
                            Name = "Radio Link"
                        });
                });

            modelBuilder.Entity("WebApp.Domain.IncidentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("IncidentTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            Code = "ASB",
                            Name = "Anti-Social Behaviour"
                        },
                        new
                        {
                            Id = 2,
                            Active = true,
                            Code = "CRM",
                            Name = "Criminal"
                        },
                        new
                        {
                            Id = 3,
                            Active = true,
                            Code = "CS",
                            Name = "Community Safety"
                        },
                        new
                        {
                            Id = 4,
                            Active = true,
                            Code = "TRF",
                            Name = "Traffic"
                        });
                });

            modelBuilder.Entity("WebApp.Domain.Operator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("EmployeeId")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId")
                        .IsUnique();

                    b.ToTable("Operators");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            Email = "john@example.com",
                            EmployeeId = "EMP001",
                            Name = "John Smith"
                        },
                        new
                        {
                            Id = 2,
                            Active = true,
                            Email = "jane@example.com",
                            EmployeeId = "EMP002",
                            Name = "Jane Doe"
                        },
                        new
                        {
                            Id = 3,
                            Active = true,
                            Email = "bob@example.com",
                            EmployeeId = "EMP003",
                            Name = "Bob Wilson"
                        });
                });

            modelBuilder.Entity("WebApp.Domain.Watch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Watches");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            Code = "MON",
                            Name = "Morning"
                        },
                        new
                        {
                            Id = 2,
                            Active = true,
                            Code = "AFT",
                            Name = "Afternoon"
                        },
                        new
                        {
                            Id = 3,
                            Active = true,
                            Code = "EVE",
                            Name = "Evening"
                        },
                        new
                        {
                            Id = 4,
                            Active = true,
                            Code = "NIT",
                            Name = "Night"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
